export const DNS_BRIDGED_CC = "bridged.cc"
export const DNS_BRIDGED_XYZ = "bridged.xyz"
export const HOSTING_SERVICE_HOST = "https://hosting.bridged.cc"
export const URL_SERVICE_HOST = "https://bridged.cc"
export const DESIGN_STORE_SERVICE_HOST = "https://desing-store.bridged.cc"