export const DNS_BRIDGED_CC = "bridged.cc"
export const DNS_BRIDGED_XYZ = "bridged.xyz"
export const HOSTING_SERVICE_HOST = "https://hosting.bridged.cc"
export const URL_SERVICE_HOST = "https://bridged.cc"
export const DESIGN_STORE_SERVICE_HOST = "https://desing-store.bridged.cc"
export const SCENE_STORE_SERVICE_HOST = "https://scene-store.bridged.cc"
export const G11N_SERVICE_HOST = "https://g11n.bridged.cc"
export const ASSET_SERVICE_HOST = "https://assets.bridged.cc"
